a=float(input("Enter the first number"))
b=float(input("Enter the second number"))
print("sum is ",a+b)
print("Difference is ",a-b)
print("product is ",a*b)
print("division is ",a/b)
print("modulus is ",a%b)
print("exponential is ",a**b)
print("floor division is",a//b)
